### ISSUE TITLE
realpath is POSIX.1-2001 compliant instead of POSIX.1-2008

### ISSUE THREAD

**Issue by xdelatour** [freemint/mintlib#47]
The [realpath()](https://man7.org/linux/man-pages/man3/realpath.3.html) function is only compatible with posix version POSIX.1-2001. ie the function fails when the second parameter is null.

opkg calls realpath() three times with a null pointer as second parameter and therefore does not work.

The solution is to replace realpath(filename, NULL) with canonicalize_file_name(filename) which works as expected.

Another possibility is to update the mintlib, which seems better to me, but I don't know which glibc version the current mintlib corresponds to

**Comment by th-otto** [comment]
Yes, i already noticed that recently too. And i wondered about it, because the internal function canonicalize already handles the case where resolved is null. Maybe we can just remove the check in realpath?

>I don't know which glibc version the current mintlib corresponds to

You cannot really tell. I think it initially started with glibc 2.1, but not all new features that were implemented since then have been ported to mintlib. For example all the openat(), statat() etc. functions are missing. Most of the time this is not a problem, because packages using them already have fallbacks using gnulib. But we just don't have the manpower to follow glibc development.

**Comment by xdelatour** [comment]
> But we just don't have the manpower to follow glibc development.

Indeed :-(
- glibc-2.1.1.tar.gz: 8.4 MB (unpacked: 6438 items, 55.3 MB)
- glibc-2.37.tar.gz: 37.1 MB (unpacked: 20197 items, 240.2 MB)

**Comment by mikrosk** [comment]
In this context newlib or ulibc or similar make more sense.

However a long time ago I once proposed this to Frank Naumann and his reply was very simple and pragmatic: is there something _significant_ missing in mintlib so it makes sense to completely drop it? Isn't easier just to implement the missing feature? And it's made sense. So after that I'm more cautious with the question of replacement for something else.

**Comment by th-otto** [comment]
Well, you can't really compare the pure size of mintlib vs glibc. For certain features, it currently doesn't make sense to implement them. Eg. glibc contains both libintl & iconv. If we would implement that, executables would be i think around 2MB as long as we don't have loadable modules. Also, for libintl to work, you would need locales support.

There are also other large areas of functions which are of little use (ie all the 128bit functions, both for integer & float). I haven't even seen any linux program so far that needs them.

**Comment by xdelatour** [comment]
For info only:
- [Old comparison between libc](https://www.etalabs.net/compare_libcs.html) (maybe not very relevant: comparison made by the musl's editor and musl is Linux-specific)
- [realpath in glibc 2.32 (247 lines)](https://sourceware.org/git/?p=glibc.git;a=blob_plain;f=stdlib/canonicalize.c;hb=refs/heads/release/2.32/master) few changes between mintlib and glibc
- [realpath in glibc 2.33 (475 lines)](https://sourceware.org/git/?p=glibc.git;a=blob_plain;f=stdlib/canonicalize.c;hb=refs/heads/release/2.33/master)
- [Full list of POSIX.1-2017 functions](https://pubs.opengroup.org/onlinepubs/9699919799/idx/functions.html)

**Comment by xdelatour** [comment]
Hi Thorsten,

I tried the following patch to sync `realpath()` with glibc 2.32 successfully but it looks a bit dirty (I made all tests without `assert()` and added them later). I have removed your lines about gcc 12 and compiled with gcc 9.3.1. Finally I'm not familar with typeof neither weak_alias.

Nevertheless, it compiles and opkg compiles too with your build script and patch without any change to upstream tarball of opkg 0.6.1.

Of course, I checked opkg is working and is able to install and update packages.

[canonicalize.c.patch.txt](https://github.com/freemint/mintlib/files/11069431/canonicalize.c.patch.txt)

**Comment by th-otto** [comment]
Thanks, pushed now. I removed the assertions however, i think they are not needed and will only add unneeded code.

The business about typeof() is to pacify -Wmissing-prototypes, because only the function without leading underscores is declared in the header.

The ifdef for GCC 12 was only needed because alloca was used previously, which made gcc think the function would return a local address from the function.
